services:

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - cdp-tenant

  
  postgres:
    image: postgres
    restart: always
    shm_size: 1000mb
    networks:
      - cdp-tenant
    env_file:
      - 'compose/aws.env'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: windturbine_service_db
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s



  node-c-2-backend:
    build:
      context: .
      target: development
    ports:
      - '3001:3001'
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3001
      NODE_ENV: development
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
